name: CI

on: [push]
# on:  
#   schedule:    
#     - cron: 0 15,18,21 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Save data
      run: |
        FILE=./`date +"%Y-%m-%d"`.json
        if [ -f "$FILE" ]; then
          echo "$FILE exists. Done for today."
        else
          echo "Get today's data"
          wget -O $FILE https://dati.comune.milano.it/dataset/e340a8c6-b68b-49e8-9569-910f31865489/resource/edf8dcee-c1f4-41fe-957e-c7cd16f366c9/download/qaria_datoariagiornostazione_`date +"%Y-%m-%d"`.json
          echo "$FILE saved."
        fi
    - name: git check in
      env:
        GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }} 
        PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: |
        git config user.email "$GIT_OWNER_EMAIL"
        git config user.name "fabiovalse"
        if [[ `git status --porcelain` ]]; then
          git add .
          git commit -a -m "Add new daily data."
          git remote rm origin
          git remote add origin https://fabiovalse:$PUSH_TOKEN@github.com/fabiovalse/data-collector.git
          git push origin HEAD:main
        else
          echo 'unable to detech changes'
        fi
